version: 2
updates:
- package-ecosystem: maven
  directory: "/spring-app"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework:spring-tx
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: org.hibernate:hibernate-validator
    versions:
    - 6.1.5.Final
